### ISSUE TITLE
JSF <h:commandLink> does not work with ignore-selector

### ISSUE THREAD

**Issue by matinh** [snikch/jquery.dirtyforms#107]
DirtyForms works pretty well with JSF. But when I have a simple command-link like this: 

    <h:commandLink action="#{someAction}" value="click me" styleClass="dirtyignore" />

the ignore-selector does not work. The JSF link renders as the following HTML code:

    <a class="dirtyignore"
       onclick="jsf.util.chain(this,event,'mojarra.jsfcljs(document.getElementById(\'editForm\'),{\'editForm:j_idt548\':\'editForm:j_idt548\'},\'\')');return false"
       href="#">click me</a>

As you can see, the ignore-class "dirtyignore" is present on the generated HTML. Still, the element is not ignored and the dialog opens, whenever the form is dirty and the link clicked.

I also tried adding the "dirtyignore" class to a surrounding tag without success. However, I found a workaround by adding

    onclick="$('html').addClass($.DirtyForms.ignoreClass);"

to the commandLink. This disables DirtyForms completely as mentioned in the documentation. This way the click executes as expected.

Any idea what I'm doing wrong? Or is it a bug?

**Comment by NightOwl888** [comment]
It sounds like you have a different value than `dirtyignore` for the `ignoreClass`. Is the value of `$.DirtyForms.ignoreClass` returning `dirtyignore`?

Do note that you can set it to any value using options. 

```js
$('form').dirtyForms(ignoreClass: 'mydirtyignore');
```

Also, the default value in Dirty Forms 1.x was `ignoredirty`, not `dirtyignore`.

**Comment by matinh** [comment]
I did not change the `ignoreClass` to anything else then `dirtyignore`. I am using DirtyForms 2.0.0 and `$.DirtyForms.ignoreClass` gives me `dirtyignore`. In the source code I see `dirtyignore` but nowhere `ignoredirty`.

The ignore-feature works very-well for all other links and buttons, so I assume the value of the `ignoreClass` is not the problem. Just JSF commandLinks (resp. the resulting HTML) seem broken.

I created a small test-page within my application with various links (JSF page, but I created the links as plain HTML links) and the following **does not** work (the click on the link is **not** ignored):

    <a class="dirtyignore" href="#" onclick="mojarra.jsfcljs(document.getElementById('editForm'),{'editForm:j_idt549':'editForm:j_idt549'},'');return false">jsf-link</a><br/>

while this **does** work (a click on this link **is** ignored as expected):

    <a class="dirtyignore" href="#" onclick="return false;">onClick-link</a>

So it seem the magic behind the JSF script breaks something.
Any ideas?

**Comment by NightOwl888** [comment]
I suspect this has something to do with the onclick event being set manually by JSF. It would be helpful to have a working sample (posted here as an HTML document) so I can see if this is a bug that needs to be addressed.

In the meantime, you could [customize the event binding](https://github.com/snikch/jquery.dirtyforms#event-handler-customization) to not attach the click event rather than allow Dirty Forms to attach the event and then subsequently ignore it on each click.

```
<h:commandLink action="#{someAction}" value="click me" styleClass="jsfignore" />

$(document).bind('bind.dirtyforms', function (ev, events) {
	events.bind = function (window, document, data) {
		$(window).bind('beforeunload', data, events.onBeforeUnload);
		// Add an exception for jsfignore class for event binding
		$(document).on('click', 'a:not([target="_blank"],[class="jsfignore"])', data, events.onAnchorClick)
			.on('submit', 'form', data, events.onSubmit);
	};
});

// Make sure the above is before the first call
// to dirty forms.
$('form').dirtyForms();
```

**Comment by matinh** [comment]
Thank's for the hint with the event-binding. I was actually thinking, that something like this would work... but I'm really a lousy JavaScript programmer and thus avoided the work ;-)

Regarding the sample-page: I'm currently busy with other things and don't have a plain HTML page at hand, but I'll try to create a SSCCE page for you to reproduce. But it will probably take me a week or two.

**Comment by matinh** [comment]
Ok, so finally I found some time to create a minimalistic reproducer. (Unfortunately attaching files to this issue doesn't work for me, so I put them on pastebin.com and link to them.)

There is a [JSF page](http://pastebin.com/QL2aUPm7) that shows two text-input fields and a submit button. The second input-field and the button are set to "dirtyignore", so submitting the form via the button should IMHO never trigger a dialog. But it does!

I also included the [HTML page](http://pastebin.com/MNsC5xB7) resulting from the JSF page (slightly modified to work offline and prettified) as well as the required [jsf.js](http://pastebin.com/63arsWpT) JavaScript that is provided by JSF. BTW, I'm using Mojarra 2.2.12 with JBoss Wildfly.

To reproduce, just save the files to a local folder and open the `test-dirty.html` with your browser. Type some text in the first input field and submit it via the button. You'll get the browser's dialog asking for verification, which should not happen, because the button is set to `dirtyignore`.

Please let me know if you can reproduce the problem with these files.

**Comment by NightOwl888** [comment]
Ok, I was able to reproduce the problem. 

After some analysis, I discovered it is related to the fact that JSF calls the `form.submit()` method on your anchor click. Dirty Forms is listening for the `submit` event of the form. However [`form.submit()` doesn't call the `submit` event](http://stackoverflow.com/q/18774821/181087) so you need to do it manually. This is necessary to ensure the `beforeunload` event handler is detached before submitting the form.

I was able to get the sample to work by adding the call right before the rest of your JSF code in the onclick event.

```html
    <a id="myForm:link" href="#"
       onclick="$('#myForm').trigger('submit');mojarra.jsfcljs(document.getElementById('myForm'),{'myForm:link':'myForm:link'},'');return false"
       class="dirtyignore">click me</a>
```

If that is not possible to do with this framework, you might be able to do it with jQuery, but you need to [ensure this event is attached first before the JSF code is called so the events run in the right order](http://stackoverflow.com/questions/6694434/can-you-bind-click-so-that-it-fires-prior-to-onclick) (that is, the `submit` event is triggered before the `form.submit()` method is called by JSF).

Note that you can circumvent this effort if you change the form to use a submit button instead of a link, so the event is fired by the browser instead of by JavaScript.

**Comment by matinh** [comment]
Thanks's for your analysis! So if I got you right, DirtyForms cannot do anything about this, because the submit-event of the `form` never happens and this is due to how JSF submits the form. Too bad :(

The good news are: triggering the form's submit-event via jQuery is easily possible (based on your suggestion). In JSF you just have to add some onclick-JavaScript to do that:

    <h:commandLink action="#{someAction}"
                   onclick="$(this).parent('form').trigger('submit')"
                   value="click me" styleClass="dirtyignore" />

So I'll close this issue now, as it is not a bug and and a workaround exists.

Thx again for your help!
