### ISSUE TITLE
On opening a modal dialog, df clears the beforeunload event

### ISSUE THREAD

**Issue by nrob81** [snikch/jquery.dirtyforms#114]
I have a form with df, and a link to open some modal dialog. 
When the dialog opens, it clears the beforeunload event.
How can be set up to continue checking my form after I close the modal dialog?

console logs:
[DirtyForms] Adding form w0 to forms to watch
[DirtyForms] Storing original value for _csrf
[DirtyForms] Storing original value for Prenajom[r1]
[DirtyForms] Storing original value for Prenajom[r2]
[DirtyForms] Storing original value for Prenajom[r3]

//here I open a modal
[DirtyForms] Entering: Leaving Event fired, type: click, element: http://k.local/dppo/note?id=10&model=Prenajom&attribute=r1, class: btn btn-default popup-addon-table and id: 
[DirtyForms] Leaving: Not dirty
[DirtyForms] Clearing the beforeunload event

//close modal and write something to my form
[DirtyForms] Setting dirty status to true on field prenajom-r1
[DirtyForms] Setting dirty status to true on form w0
[DirtyForms] Setting dirty status to true on field prenajom-r1
[DirtyForms] Setting dirty status to true on form w0

//click away
[DirtyForms] Entering: Leaving Event fired, type: click, element: [object HTMLImageElement], class: png and id:

and my beforeunload were not called.
what can i do to reactivate this event when i close my modal dialog?
Thanks!

**Comment by NightOwl888** [comment]
It sounds like you need to ignore the link that opens the dialog. By default, Dirty Forms considers every anchor click to be an attempt to navigate away from the page, regardless of whether it does or not. To ignore the link, see [ignoring things](https://github.com/snikch/jquery.dirtyforms#ignoring-things).

**Comment by nrob81** [comment]
A tried to ignore that link, but did not worked. I seaw this in the console:

'Entering: Leaving Event fired, type: click, element: [object HTMLElement], class: glyphicon glyphicon-list and id: 
[DirtyForms] Leaving: Element has ignore class or a descendant of an ignored element 
[DirtyForms] Clearing the beforeunload event. 

So, DF knows about what to ignore but also clears the beforeunload event and it dont warn be about change, after I close my modal.

**Comment by NightOwl888** [comment]
It is normal for Dirty Forms to detach the beforeunload event (due to some issues on older browsers) just before leaving the page. The issue you have is that *something* is telling Dirty Forms that you are leaving the page.

A common cause for the beforeunload event being detached prematurely is having misconfigured event handling code on the dialog. You keep mentioning you have a "modal", but it is unclear if your dialog is a custom Dirty Forms dialog, a pre-built Dirty Forms dialog, or a dialog that has another purpose in your application.

If a custom Dirty Forms dialog, you need to ensure the [`staySelector` and `proceedSelector`](https://github.com/snikch/jquery.dirtyforms#custom-dialog-integration) are attached correctly in every case you close the dialog [as shown in the examples](https://github.com/snikch/jquery.dirtyforms#dialog-examples), otherwise Dirty Forms will not know when the user is finished making the decision on the dialog.

If this doesn't resolve your issue, I suggest you create a standalone HTML document demonstrating the issue and posting it here.

**Comment by nrob81** [comment]
It is a custom modal to edit additional data. 

https://www.kominvent.eu/test 
Please check this link. There is only one input with an appended button.
if you click the list button, it opens my modal. (here this modal not works, you can see only a 404 error but it does not matter).
if you close the modal, df stops working. 
the link to the modal has a .ignore-me class and my code for enabling df is this:
`$(function() {  
    $('form').dirtyForms({  
        debug: true,  
        ignoreSelector: 'a.ignore-me'  
    });  
});  
`

**Comment by NightOwl888** [comment]
One thing wrong with your setup is that Dirty Forms should always be the last jQuery plugin in the stack [as noted in the docs](https://github.com/snikch/jquery.dirtyforms#download--installation). If you are attaching an event to the button after initializing Dirty Forms, it might not be ignoring correctly.

Also, a JS dialog normally calls `event.preventDefault()`. If you do that, you don't need an ignore selector at all.

But if all else fails, you can customize the event binding so the event is never attached to your hyperlink in the first place.

```js
$(document).bind('bind.dirtyforms', function (ev, events) {
	events.bind = function (window, document, data) {
		$(window).bind('beforeunload', data, events.onBeforeUnload);
		// Change the event binding to ignore your anchor
		$(document).on('click', 'a:not([target="_blank"],.ignore-me)', data, events.onAnchorClick)
				   .on('submit', 'form', data, events.onSubmit);
	};
});
```

**Comment by nrob81** [comment]
@NightOwl888, now I registered the df after other scripts and now it works. 
Thank you for your help!
