### ISSUE TITLE
dirtyForms is failing after user presses 'Esc' key while in 'Stay/Discard' popup.

### ISSUE THREAD

**Issue by furiabhavesh** [snikch/jquery.dirtyforms#45]
When user has a dirty form and tries to navigate elsewhere the 'Save/Discard' popup can be acted using following actions.
1) Click on close link of popup - Works fine
2) Click on "Discard changes" - Works fine
3) Click on "Stay on this page" - Works fine
4) If user presses 'Esc' key and then try to navigate elsewhere, dirtyForm fails here.

**Comment by NightOwl888** [comment]
Or maybe a year or 2? :). What dialog are you using? Could you show how you configured it? 

Note that for a modal dialog to work right when the user cancels, the default action must set (or leave) `$.DirtyForms.choiceContinue = false;` and then explicitly call `$.DirtyForms.choiceCommit(e);` when the dialog is closed. For example, with jQuery UI:

```js
	$.DirtyForms.dialog = {
		selector: '#unsavedChanges',
		fire: function(message, dlgTitle) {
			$('#unsavedChanges').dialog({title: dlgTitle, width: 450, modal: true});
			$('#unsavedChanges').html(message);
		},
		refire: function(content) {
			return false;
		},
		stash: function() {
			return false;
		},
		bind: function() {
			$('#unsavedChanges').dialog('option', 'buttons', 
				[
					{
						text: "Leave This Page",
						click: function(e) {
							$.DirtyForms.choiceContinue = true;
							$(this).dialog('close');
							
						}
					},
					{
						text: "Stay Here",
						click: function(e) {
							$(this).dialog('close');
						}
					}
				] 
			).bind('dialogclose', function(e) {
				// Execute the choice after the modal dialog closes
				$.DirtyForms.choiceCommit(e);
			});
		}
	}
```

But the exact syntax depends on which dialog framework you are using.

**Comment by furiabhavesh** [comment]
Yes, its little less than 2 years ;). I don't have access to the code where this issue was appearing. 
Although, I am attaching the code which re-produces the issue.

    <!DOCTYPE html>
    <html>
    <head>
      <title>Dirty Escape example</title>
      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
      <script src="facebox.js"></script>
      <script src="jquery.dirtyforms.js"></script>
      <link rel="stylesheet" media="all" href="facebox.css" />
    </head>
    <body>
      <form>
        <input value="Make it dirty" />
        <input type="submit">
      </form>
      <a href="https://www.google.com">Distract</a>
    </body>
    <script type="text/javascript">
      $(document).ready(function(){
        $("form").dirtyForms();
      });
    </script>
    </html>

I have manually downloaded `facebox.js`, `facebox.css` & `jquery.dirtyforms.js` for this example to save my time searching for CDN

**Comment by NightOwl888** [comment]
Thanks.

I have confirmed there is an issue. However, I haven't tracked it down yet. I did notice that when I used jQuery UI dialog instead of FaceBox this problem doesn't exist, so I suspect this has more to do with FaceBox than with dirtyForms. I even attempted to change it to the pattern of setting the boolean variable in the dialog and then calling `choiceCommit` when the dialog closed, but it made no difference in terms of functionality.

I also noticed another issue when using jQuery UI. The ESC key only works the first time the dialog is closed. Subsequent dialog boxes are not responding to the ESC key.

I will need to investigate both of these issues further when I get the chance. I am just reporting my findings here so I can remember what they were when that time comes.
