### ISSUE TITLE
TinyMCE iFrames

### ISSUE THREAD

**Issue by lalweil** [snikch/jquery.dirtyforms#51]
Hello,

I have the dirtyforms up and working on my form, but I'm having issues with TinyMCE. I'm using the WYSIWYG module in Drupal 7, and I have multiple TinyMCE instances on a single page.

Any of the fields in the form that are radio buttons or non-TinyMCE fields are trowing isDirty just fine. Any of the TinyMCE fields that are inside of their iFrames aren't triggering properly no matter how significantly the content is changing.

An example of the TinyMCE rendered html is something like...
iframe
body contenteditable="true" onload="window.parent.tinyMCE.get('edit-field-field-2-comments-und-0-value').onLoad.dispatch();" class="mceContentBody " id="tinymce" spellcheck="false" dir="ltr"><p>asdf asdf asdf asdf asdf asdf <br></p></body
/iframe

I've tried experimenting with the tinycme helper that comes with dirtyforms, but I don't really understand how to make it work, and it doesn't look like it is geared to look inside the iFrames in any case.

Any help would be much appreciated!

Thanks.

**Comment by samuelsolis** [comment]
I'm triying to use dirtyforms with tinyMCE too and the event is not triggering.

Really, if I read correctly, for using dirtyforms with tiny only have to include the helper. I made this include but It doesn't run correctly. The others fields run correctly.

Anybody know how to run it or can show us a little example code? 

Thanks! :-)

**Comment by NightOwl888** [comment]
@samuelsolis - Thanks for the report.

It has been some time since I worked on this project and it seems that tinyMCE suffers from extreme version creep, and has since become incompatible with dirtyforms. I couldn't get the latest 4.x version to work at all. But the latest 3.x version ([3.5.11](http://www.tinymce.com/download/download.php)) is still working.

[Here is a demo](https://github.com/NightOwl888/jquery.dirtyforms_51) showing the usage with tinymce. There are a couple of things to note:

1. You have to use the jQuery wrapper of tinyMCE.
2. TinyMCE should be initialized using the [jQuery initialization shown here](http://www.tinymce.com/wiki.php/TinyMCE3x:jQuery_Plugin).

In the demo, just edit the tinyMCE box and then click one of the 2 bold links and you will see that the dialog works. You can also click the buttons to check whether the form is dirty and to mark it clean if it is.

I will have to look into what the new method of initializing tinyMCE with jQuery is - I am not sure if it is just that I am using the wrong syntax or if there is another underlying reason dirtyforms is now incompatible with tinyMCE. In the meantime, I suggest using version [3.5.11](http://www.tinymce.com/download/download.php).

**Comment by samuelsolis** [comment]
@NightOwl888 Oh, I didn't see this answer. Now it run ok using the code that you mention in #74 

Thanks!

**Comment by NightOwl888** [comment]
@lalweil 

I realize this is probably too late, but you are correct in that the plugin is not designed to work with iFrames that are hosted within the current page. Dirty forms only works with the parent page when it is hosted within an iFrame.

See #68 for an example of iFrame usage.

Anyway, if you could describe what it is your use case is doing or better yet provide a working demo I will consider adding this feature.

**Comment by NightOwl888** [comment]
FYI - Dirty Forms 2.0 BETA is now available. The "IFrame support" (which really only covered a specific use case) has been replaced with customizable event binding, which should cover any use case with IFrames, and a lot more.

Please give it a try and report any issues you find. Thanks.
