### ISSUE TITLE
opt out of facebox

### ISSUE THREAD

**Issue by jtmkrueger** [snikch/jquery.dirtyforms#70]
I'd prefer to just use confirm, and not have to use facebox. Being able to initialize without facebox would be really nice. For now I'm just going to remove refs to it.

**Comment by thinsoldier** [comment]
It seems to work fine without facebox on actual form fields. The only problem I encounter is when clicking a link. The first click will attempt to execute code that relies on facebox and will fail. The 2nd click will navigate away from the current page without dirtyforms asking for confirmation. 

Surely there must be some way to have links trigger the default dialog instead of facebox the same way dirty form elements can.

**Comment by NightOwl888** [comment]
The [documentation](https://github.com/snikch/jquery.dirtyforms#dialogs) says to set the dialog to `false` in order to disable it.

```js
$.DirtyForms.dialog = false;
```

It doesn't seem to work, though.

I am planning to make a 2.0 version that uses the default dialog by default and has add-on packages for popular dialogs. For backward compatibility reasons, it can't just be yanked out of the current version. But I would like to fix the 1.x version so it works with no dialog by setting it to false the way the documentation specifies, or I will gladly accept a pull request for same if someone beats me to it.
