### ISSUE TITLE
dirtyForms.setDirty

### ISSUE THREAD

**Issue by jmengelle** [snikch/jquery.dirtyforms#89]
hi,

I’m missing a feature (or i didn’t find) : I want to explicitly tell that a form is dirty  (like setClean)
 
The reason behind that is form validation (server side).
When I have validation error and reload my page with errors, I would like to set my form to dirty.

Also, the reset button would keep this dirty state. 

i did some local change base on setClean method, but would be great if this was native.

**Comment by NightOwl888** [comment]
As pointed out in #79, the `setDirty` method has been removed from Dirty Forms.

The primary reasons for this change are as follows:

1. This is redundant functionality to having a [helper](https://github.com/snikch/jquery.dirtyforms#helpers) return dirty/clean based on some external logic.
2. Since setting a form to dirty would automatically be "corrected" when the user interacts with the form again, it seems to have little value.

See the comment [here](https://github.com/snikch/jquery.dirtyforms/issues/79#issuecomment-121611560) for the proper way to read the dirty/clean state based on external logic.

Also, I firmly believe that if we had a `setDirty` field, it should do exactly the opposite of `setClean`. To do anything but would be illogical. `setClean` resets the state of each field to clean, and basically makes it "forget" it was dirty. But there is no logical way to make a `setDirty` method provide inverse behavior that is sensible.

Since resetting the form calls `setClean` directly, you are basically saying that the `setDirty` method should not be affected by `setClean`. Again, I disagree on this point.

**Comment by jmengelle** [comment]
The helper example realy help me (i'm not at all a main JS developer)
If i have time, i will use that instead of editing the lib js file, look more clean ;)

But while it's covenient, i still believe that setDirty should be in the plugin, for the same reason there is a setClean method. 

Just to say, in "my" setDirty, basically what i do (base on setClean) : 
- remove the call to storeOriginalValue($field); 
- replace setDirtyStatus($field, false) by setDirtyStatus($field, true); 

So the point is that i don't care about the field value, i just want to got my form state be as dirty. 
In my mind, the setClean/setDirty should only manage status (and a reset Method would do the job of reset value and make it clean). 

Forget about resetting, i agree with you on this point. If i call "setDirty" because of some external logic, i should also manage the need to call it again (or not) if the form is reset.
