### ISSUE TITLE
File fields not working

### ISSUE THREAD

**Issue by davidbankes** [snikch/jquery.dirtyforms#91]
#86 mentions file fields not working, but then is closed with no solution noted, as the person who posted that issue created a workaround (but did not post the workaround). This is still a bug. Any chance for a solution in the package?

**Comment by NightOwl888** [comment]
#86 mentions nothing about file fields. Could it be that you intended to refer to a different issue?

Also, as per [the Options documentation](https://github.com/snikch/jquery.dirtyforms#options), file fields are disabled by default. To enable, you need to change the `fieldSelector` property from the default value of:

```
 input:not([type='button'],[type='image'],[type='submit'],[type='reset'],[type='file'],[type='search']),select,textarea
```

To:

```
 input:not([type='button'],[type='image'],[type='submit'],[type='reset'],type='search']),select,textarea 
```

Most people do not need to validate file fields or search fields, so this is the default setting. But since some people do, this was made a public option in version 2.0.

That being said, I haven't specifically tested with file fields, so let me know if this is working correctly or not. I will leave this issue open until I hear your reply.

**Comment by davidbankes** [comment]
I meant to reference #46.

However, I had missed that point in the documentation, which solved my problem. Apologies and thanks!
