### ISSUE TITLE
How to make form dirty manually?

### ISSUE THREAD

**Issue by udoless** [snikch/jquery.dirtyforms#93]
I need a api like this: `$('form').dirtyForms('setDirty');`

**Comment by NightOwl888** [comment]
You can "set dirty" the form by adding a custom helper. 

```js
var myIsDirty = function($node, index) {
    if ($node.is('form')) {
        // Return true if the page is currently dirty.
        return $node.hasClass('mydirty');
    }
}

$('form').dirtyForms({ 
    helpers: [
        {
             isDirty: myIsDirty
        }
    ] 
});
```

Then it is just a matter of adding your class to the form.

```js
// Set the form dirty
$('theform').addClass('mydirty');

// Set the form clean
$('theform').removeClass('mydirty');
```

See #89 and #79 for more details.

Alternatively, you can revert to the state management of version 1.2.3, which had a `setDirty` method like you are describing, but it was removed because it is essentially duplicate functionality of the helper and using real-time state management of the values makes this a grey area with lots of edge cases anyway.
