### ISSUE TITLE
After submitting a form using AJAX, the dialog does not appear if I redirect to another page when the changes has been made

### ISSUE THREAD

**Issue by sky3913** [snikch/jquery.dirtyforms#94]
I have a page with multiple forms inside. Each form has a save link to post the page using jQuery AJAX.

I initiate the dirtyform in th following way:
`$('form').dirtyForms();`

so, it will be applied to all of the forms.

When I made the changes into the form and then try to redirect to another page, the dialog will appear, but if I saved it first and made a changes then redirect to another page, the dialog won't appear.

Here is the code to save the form:

```
$(document).on('click', '#btnSaveStage1Steps1_3', function (e) {
	e.preventDefault();
	
	if ($(this).attr('disabled') == 'disabled') {
		return false;
	}

	$('#frmStage1Steps1_3').submit();
});

$(document).on('submit', '#frmStage1Steps1_3', function (e) {
	e.preventDefault();

	var serializeForm = $(this).serialize();
	var url = $(this).attr('action');

	$.ajax({
		url: url,
		type: 'POST',
		data: serializeForm,
		beforeSend: function (e) {
			$.blockUI();
		}
	}).done(function (result) {
		if (result.success) {
			alert('Saved');
		}
	}).always(function () {
		$.unblockUI();
                $('#frmStage1Steps1_3').dirtyForms('setClean');
	});
});
```

I added `$('#frmStage1Steps1_3').dirtyForms('setClean');` after `$.unblockUI();` to clear the dirty class (I've seen in the view source, after the page is posted, the `dirty` class is still there) but it doesn't work. If I checked the form and made a changes, a `dirty` class is added into the form, but why if I redirect to another page the dialog won't appear?

Please help me to solve this issue?

**Comment by NightOwl888** [comment]
The problem here is that Dirty Forms [attaches its own event handler to the form 'submit' event](https://github.com/snikch/jquery.dirtyforms/blob/master/jquery.dirtyforms.js#L284), which when fired [will detach the `beforeunload` event handler](https://github.com/snikch/jquery.dirtyforms/blob/master/jquery.dirtyforms.js#L521) if the form is dirty because an assumption is made that when the `submit` event fires, the form will be submitted, which will reset the page back to a "clean" state. Since this round trip is not happening due to the AJAX approach, you need to mimic what happens yourself.

You are already setting the form clean, which is good. But you also need to ensure the 'beforeunload` event handler is attached. Since the "detach" affects every form on the page, not just the current one, you should [customize the event handling](https://github.com/snikch/jquery.dirtyforms#event-handler-customization) to ensure this one form does not fire its default event handler. Rather than re-attaching the `beforeunload` event, you can simply remove the `submit` event from your form, which will prevent the `beforeunload` event from being detached in the first place.

```js
$(document).bind('bind.dirtyforms', function (ev, events) {
	events.bind = function (window, document, data) {
		$(window).bind('beforeunload', data, events.onBeforeUnload);
		
		// Exclude your form from the submit event
		$(document).on('click', 'a:not([target="_blank"])', data, events.onAnchorClick)
				   .on('submit', 'form:not("#frmStage1Steps1_3")', data, events.onSubmit);
	};
});


$('#watched-form').dirtyForms();

// Attach your own event handler to the form submit event
$(document).on('submit', '#frmStage1Steps1_3', function (e) {
    e.preventDefault();

    var serializeForm = $(this).serialize();
    var url = $(this).attr('action');

    $.ajax({
        url: url,
        type: 'POST',
        data: serializeForm,
        beforeSend: function (e) {
            $.blockUI();
        }
    }).done(function (result) {
        if (result.success) {
            alert('Saved');
        }
    }).always(function () {
        $.unblockUI();
                $('#frmStage1Steps1_3').dirtyForms('setClean');
    });
});
```

**Comment by sky3913** [comment]
Great...it works. Thank you for the explanation, it is clear now
